--SEE THE METADATA
SELECT * FROM INFORMATION_SCHEMA.TABLES
SELECT *FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='dim_customers'

--EXPLORE ALL COUNTRIES OUR CUSTOMERS COME FROM
SELECT DISTINCT country from gold.dim_customers

--EXLORE ALL CATEGORIES 
SELECT DISTINCT category ,subcategory,product_name from gold.dim_products
order by 1,2,3

--Find the date of the first and last order
SELECT MIN(order_date)  as first_order_date from gold.fact_sales;

SELECT MAX(order_date) as last_order_date from gold.fact_sales;

--HOW MANY YEARS OF SALES ARE AVAIABLE
SELECT DATEDIFF(YEAR,MIN(order_date),MAX(order_date)) as Order_range_years
from gold.fact_sales;

--HOW MANY MONTH OF SALES ARE AVAIABLE
SELECT DATEDIFF(MONTH,MIN(order_date),MAX(order_date)) as Order_range_months
from gold.fact_sales

--FIND YOUNGEST AND OLDEST CUSTOMER
SELECT MIN(birthdate) as oldest_customer,DATEDIFF(year,MIN(birthdate),getdate()) as oldest_customer_age,
       MAX(birthdate) as youngest_customer,DATEDIFF(year,MAX(birthdate),getdate()) as newest_customer_age
from gold.dim_customers;

--FIND THE TOTAL SALES
SELECT SUM(sales_amount) as total_sales from gold.fact_sales;

--FIND HOW MANY ITEMS ARE SOLD
SELECT SUM(quantity) as total_orders from gold.fact_sales;

--FIND THE AVERAGE SELLING PRICE
SELECT AVG(price) as avg_price from gold.fact_sales;

--FIND THE TOTAL NUMBER OF ORDERS
SELECT COUNT( DISTINCT order_number) as total_orders from gold.fact_sales

--FIND THE TOTAL NUMBER OF PRODUCTS
SELECT COUNT( DISTINCT product_key) as total_products from gold.dim_products

--FIND THE TOTAL NUMBER OF CUSTOMERS
SELECT COUNT( DISTINCT customer_key) as total_customers from gold.dim_customers

--FIND THE TOTAL NUMBER OF CUSSTOMERS TAHT PLACED AN ORDER
SELECT COUNT( DISTINCT customer_key) as total_customers from gold.fact_sales


-- Generate a Report that shows all key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Products', COUNT(DISTINCT product_name) FROM gold.dim_products
UNION ALL
SELECT 'Total Customers', COUNT(customer_key) FROM gold.dim_customers;


--FIND THE TOTAL CUSTOMERS BY COUNTRY
SELECT country ,COUNT ( DISTINCT customer_id) AS TOTAL_CUSTOMER_COUNTRY FROM gold.dim_customers
GROUP BY country

--FIND THE TOTAL  CUSTOMERS BY GENDER
SELECT gender ,COUNT ( DISTINCT customer_id) AS TOTAL_CUSTOMER__GENDER FROM gold.dim_customers
GROUP BY gender

--FIND THE TOTAL PRODUCTS BY CATEGORY
SELECT category,SUM( DISTINCT product_id) as TOTAL_PRODUCTS_CATEGORY FROM gold.dim_products
GROUP BY category    
--AVERAGE COSTS IN EACH CATEGORY
SELECT category,AVG(cost) as AVG_PRODUCT_ID FROM gold.dim_products
GROUP BY category
--FIND THE TOTAL REVENUE GENERATED BY EACH CUSTOMERS
SELECT dc.customer_key,
        SUM(fs.sales_amount) as TOTAL_SALES_AMOUNT 
FROM gold.fact_sales as fs 
JOIN  gold.dim_customers as dc
on dc.customer_Key=fs.customer_key
group by dc.customer_key

--FIND THE TOTAL REVENUE GENERATED BY EACH CATEGORY?
SELECT dp.category,
        SUM(fs.sales_amount) as TOTAL_SALES_AMOUNT 
FROM gold.fact_sales as fs 
JOIN  gold.dim_products as dp 
on dp.product_Key=fs.product_key
group by dp.category

--WHAT IS DISTRUBUTION OF SOLD ITEMS ACROSS COUNTRIES?
SELECT dc.country,
        SUM(fs.quantity) as TOTAL_QUANTITY,
        SUM(fs.sales_amount) as TOTAL_SALES_AMOUNT 
FROM gold.fact_sales as fs 
JOIN  gold.dim_customers as dc 
ON dc.customer_key=fs.customer_key
GROUP BY dc.country;



--which 5 products generate the highest revenue?
SELECT *
FROM (
SELECT p.product_name,SUM(f.sales_amount) as total_sales,
        RANK() OVER( order by Sum(f.sales_amount) DESC) as rnk
FROM gold.fact_sales as f
LEFT JOIN gold.dim_products as p
on p.product_key=f.product_key 
Group by p.product_name
)t
where rnk<=5 ;

--which 5 products generate the lowest revenue?
SELECT *
FROM (
SELECT p.product_name,SUM(f.sales_amount) as total_sales,
        RANK() OVER( order by Sum(f.sales_amount) asc) as rnk
FROM gold.fact_sales as f
LEFT JOIN gold.dim_products as p
on p.product_key=f.product_key 
Group by p.product_name
)t
where rnk<=5 ;

--FIND THE TOP 10 CUSTOMERS WITH HIGHEST REVENUE
SELECT top 10
c.customer_key,c.first_name,c.last_name ,SUM(f.sales_amount) as total_sales
FROM gold.fact_sales as f
LEFT JOIN gold.dim_customers as c
on c.customer_key=f.customer_key 
Group by c.customer_key,c.first_name,c.last_name
ORDER BY total_sales DESC;

--FIND THE TOP 3 CUSTOMERS WITH FEW ORDERS
SELECT top 3
c.customer_key,c.first_name,c.last_name,COUNT( DISTINCT f.order_number) as total_orders
FROM gold.fact_sales as f
LEFT JOIN gold.dim_customers as c
on c.customer_key=f.customer_key 
Group by c.customer_key,c.first_name,c.last_name
ORDER BY total_orders ASC;
